### PR TITLE
Add new controls for use in PCI sims

### PR DESCRIPTION
**Pull request by mklewandowski**
This PR adds 3 new components that are required for the 6 PCI sims that we are building.  New components include:
- a progress bar to show the simulation time/progress
- a VCR button that can be used to show a Play/Pause button or a Rewind button
- a Save button

These components are styled (including hover/active states) to be used with the 6 PCI sims.  We can add additional props if these components end up being needed in other applications, but for now they are all essential for the suite of PCI sims.

You can easily take a look at the new components by cloning the repo, running `yarn install`, and then running `yarn run storybook`. 

new-controls

### CODE REVIEW

**Review by dougmartin — APPROVED** [review]
Looks good.   Each of these components is a pure function already but we are using classes to encapsulate the code.  Was there a reason not to use functions?  Was it just to avoid having to use hooks?  I'm just curious - I don't think it needs to change.

**Review by kswenson — COMMENTED** [review]
Code looks fine. I echo @dougmartin's question about why a few components were written as classes even though they seem well-suited to be functional components like all the others, but that's a minor concern.

My larger question is about the possible implications of introducing styled-components into other projects using these components (e.g. DESE). (I'd forgotten that this project used styled-components for styling.) Are there any issues with mixing styled-components with SASS/SCSS styling we should consider? Any issues with loading styled-components into other environments (e.g. testnav)? Any collaboration concerns, e.g. might the use of styled-components be a barrier for any project partners?

**Comment by mklewandowski** [comment]
@dougmartin @kswenson A couple of notes:
- I only used class components as I was following the structure of the existing components in the library.  I'll be coming back to this library with other changes so if time permits, I'll refactor them into function components.
- On styled components.  I have the same concerns, and I'm not crazy about styled components.  That said, I did tests using a couple of the components in the DESE models project running in the test harness, and I haven't hit any issues yet.  There will probably only be one or two more components going in here for the DESE project (I assume the thumbnail chooser lives elsewhere), but I think it does raise concerns if this repo is designed to be the place where general purpose components are supposed to live (it looks like at present it's only been used for a few CLUE components).

**Comment by mklewandowski** [comment]
@dougmartin @kswenson I went ahead and refactored the new components as function components.

**Comment by kswenson** [comment]
>it looks like at present it's only been used for a few CLUE components

@knowuh built it originally when working on the CLUE teacher dashboard. One possibility is that it still makes sense for the new components you've written to be in a separate library, but that library might not be this one.

**Comment by mklewandowski** [comment]
I think it's safe to build here unless there are major objections.  We'll have to take a few steps back if we want to start this process over somewhere else.

**Comment by mklewandowski** [comment]
I merged, but I raised the general question on Slack about where these components should live.  I'll hold off on going further until we're all in agreement.

**Pull request merged**
