### PR TITLE
Update to version 0.5.0

### PR DESCRIPTION
**Pull request by mklewandowski**
Bump to version 0.5.0 in preparation of release.

### CODE REVIEW

**Review by dougmartin — CHANGES_REQUESTED** [review]
You should run `npm i` to get the `package-lock.json` to update its version.

**Comment by mklewandowski** [comment]
> You should run `npm i` to get the `package-lock.json` to update its version.

Yeah I wasn't sure about that since we install dependencies and build this repo with yarn and running `npm install` results in a large number of changes to `package-lock.json`.  Subsequent builds before I started working on this repo also didn't touch the the lock file.  Thoughts?

**Comment by dougmartin** [comment]
`yarn i` might also work.

**Comment by kswenson** [comment]
You can also use [yarn version](https://yarnpkg.com/cli/version).

**Review by kswenson — APPROVED** [review]
👍

**Comment by mklewandowski** [comment]
None of these options update the version in the package-lock.json except using `npm install`.  Taking a step back, do we even need the `package-lock.json` at this point?  This repo has a `yarn.lock` file and all of the instructions in the readme are for using yarn.  Maybe I'm lost, but why is there a `package-lock.json` if this repo doesn't use `npm`?

**Comment by kswenson** [comment]
`npm version` updates the `package-lock.json` as well. The project should have either a `package-lock.json` or `yarn.lock`, but not both. I would have thought that this project should be using `npm` and should therefore not have a `yarn.lock`, given that `npm` is our default except with monorepos.

**Comment by mklewandowski** [comment]
Looking at the history, this project's initial commit used yarn, then it switched to npm, and then it switched back to yarn here (with a commit comment that I love! ->"Back to yarn. Sort of working (somewhat)":
https://github.com/concord-consortium/concord-react-components/commit/3632b4ef4c68bf372934ae3940f5ce0c7aa9f3d0
So is the `package-lock.json` file only there as part of some initial churn as the project was being setup and should simply be removed?

**Comment by mklewandowski** [comment]
> `npm version` updates the `package-lock.json` as well. The project should have either a `package-lock.json` or `yarn.lock`, but not both. I would have thought that this project should be using `npm` and should therefore not have a `yarn.lock`, given that `npm` is our default except with monorepos.

- `npm version` isn't changing anything locally for me
- the project has both a `yarn.lock` and a `package-lock.json` - this seems wrong
- the project readme specifies to use yarn for all dev steps from adding/installing dependencies to publishing:
https://github.com/concord-consortium/concord-react-components/blob/master/README.md

**Comment by mklewandowski** [comment]
I'm fine with continuing to use yarn on this project since that is what it used when I started adding content.  I think the package-lock file should be removed.

**Comment by kswenson** [comment]
- `npm version` has always changed both for me, e.g. `npm version minor` will update the minor version in `package.json` and `package-lock.json` without doing a full install.
- It is likely that `yarn version minor` does the same thing for `yarn`.
- If `yarn` is what this project is using then the `package-lock.json` should be removed.

**Comment by mklewandowski** [comment]
> * `npm version` has always changed both for me, e.g. `npm version minor` will update the minor version in `package.json` and `package-lock.json` without doing a full install.
> * It is likely that `yarn version minor` does the same thing for `yarn`.
> * If `yarn` is what this project is using then the `package-lock.json` should be removed.

- On npm version: Ah, I see my issue - it's because `npm version` adds a git commit too!  So github desktop wasn't showing any changes that needed to be committed because it already made the commit.  But if I do a `git status` then I see that I'm one commit ahead of the branch (the version change).  So, yes, it does indeed work.  I just wasn't expecting it to make a git commit as well.
- I'm going to remove the package-lock.json.

**Comment by kswenson** [comment]
>On npm version: Ah, I see my issue - it's because npm version adds a git commit too!

I usually do it with `--no-git-tag-version` which would then behave the way you expect. I would have designed it so it defaulted to _not_ tagging, but they didn't consult me. 😉

**Comment by mklewandowski** [comment]
> > On npm version: Ah, I see my issue - it's because npm version adds a git commit too!
> 
> I usually do it with `--no-git-tag-version` which would then behave the way you expect. I would have designed it so it defaulted to _not_ tagging, but they didn't consult me. 😉

😄 I agree, the default is odd!  Anyway, I think, after much discussion, this is ready to merge and then I can publish the new version (package-lock is now gone).

**Pull request merged**
